"""empty message

Revision ID: 39939c989fb1
Revises: None
Create Date: 2013-11-06 21:00:45.655405

"""

# revision identifiers, used by Alembic.
revision = '39939c989fb1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('downs', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('user', sa.Column('ups', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('user', 'profession_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profession_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'ups')
    op.drop_column('user', 'downs')
    ### end Alembic commands ###
